services:
  notifier-service:
    build:
      context: ./notifier-service
      dockerfile: Dockerfile
    container_name: notifier-service
    ports:
      - "8082:8082"

  edge-detector:
    build:
      context: ./edge-detector
      dockerfile: Dockerfile
    container_name: edge-detector
    environment:
      APP_NOTIFIER_BASE_URL: http://notifier-service:8082
    depends_on:
      - notifier-service
    ports:
      - "8081:8081"
